name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  unit_tests:
      runs-on: ubuntu-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

      steps:
      - uses: actions/checkout@v2

      - name: Build code
        run: |
          git submodule update --init --recursive
          mkdir build && cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DBUILD_CODE_COV=ON ..
          make